---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  host_ip: 127.0.0.1
  host_port: 2231
  # Worker IPs are simply incremented from the control IP.
  control_ip: 10.0.0.10
  ssh_port: 22
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
gateway:
  host_ip: 127.0.0.1
  host_port: 2251
  guest_ip: 10.0.0.15
  ssh_port: 22
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  bridge_nic: wlp0s20f3
  pub_in: eth2
  priv_out: eth1
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 2
    cpu: 1
    memory: 2048
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
shared_folders:
  - host_path: ../../
    vm_path: /mnt
software:
  box: bento/debian-12
  calico: 3.26.0
  # To skip the dashboard installation, set its version to an empty value or comment it out:
  dashboard: 2.7.0
  kubernetes: 1.29.0-*
  os: wormwood
