apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  namespace: resource-cap-example
spec:
  containers:
  - name: resource-demo-container
    image: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "500m"