---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.245
spec:
  type: LoadBalancer # Espone il servizio su un indirizzo IP esterno
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: v1
kind: Pod
metadata:
  name: nginx-healthcheck
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
---