version: "3.6"

#######
#
# il comando corretto per lanciare un container con docker compose 
#
# docker-compose -f ./docker-compose.yml down --remove-orphans && docker-compose -f ./docker-compose.yml   up --build --force-recreate
#
#######

networks:
  nginx-network:

services:
  nginx:
    #    image: nginx:1.18.0-alpine
    build: ./DockerFiles/nginx/
    labels:
      - "nginx-reverse-proxy"
    hostname: nginx
    restart: on-failure
    networks:
      - nginx-network
    ports:
      - $HTTP_PORT:80
      - $HTTPS_PORT:443
    volumes:
      - $NGINX_HOME/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - $NGINX_HOME/conf.d/:/etc/nginx/conf.d/:ro
      - $NGINX_HOME/sites-enabled:/etc/nginx/sites-enabled:ro
      - $NGINX_HOME/sites-available:/etc/nginx/sites-available:ro
      - $NGINX_HOME/html:/etc/nginx/html:ro
      - $NGINX_HOME/logs:/var/log/nginx:rw
      - $NGINX_HOME/proxy_params:/etc/nginx/proxy_params:ro
      - $CA_HOME:/etc/ssl:ro
